DDPG:
  batch_size: 32
  exp_decay: 0.01
  lr_actor: 0.001
  lr_critic: 0.002
  memory_capacity: 300
RL:
  action_bound:
  - -3.14159
  - 3.14159
  action_discrete: false
  action_num: 1
  method: DDPG
  reward_discount: 0.9
  state_frames: 1
  state_shape: 22
  train_multi_steps: false
  train_run_steps: null
conn:
  client_num: 4
  client_retries: 3
  client_timeout: 2500
  server_backend_port: 5556
  server_frontend_port: 5555
  server_ip: 127.0.0.1
  server_worker_num: 1
log:
  gpu_memory: 0.3
  model_save_cycle: 3
  output_tf: true
  output_tf_dir: ./log
