RL:
    method: 'DQN'
    # train_multi_steps: 1       # default: 1, param: 'if_down', 'steps(int)'-> train if down or train after steps    
    reward_gamma: 0.99    
    exploration: 50        # train after exploration step
#    action_noise: 'epsilon-greedy'

DQN:
    memory_capacity: 50000
    memory_train_min: 128 
    batch_size: 64
    update_Q_target_times: 100
    lr: 0.00001

epsilon-greedy:
    value: 1.0
    discount: 0.0001   # each step discount it  

# from DQN of nature's Model architecture section: https://www.nature.com/articles/nature14236.pdf 
NN:
    1_conv: 
        type: 'conv'
        kernel_size: 8
        out_channel: 32
        stride: 4
    2_maxpool:
        type: 'maxpool'
    3_conv: 
        type: 'conv'
        kernel_size: 4
        out_channel: 64
        stride: 2
    4_conv: 
        type: 'conv'
        kernel_size: 3
        out_channel: 64
        stride: 1
    5_flatten:
        type: 'flatten'
    6_fc:
        type: 'fc'
        size: 512
    7_predict:
        type: 'fc'
        size: 2
        op: 'none'

misc:
    model_save_cycle: 1000
    gpu_memory_ratio: 0.3
    random_seed: 79             # t_82 get max reward = 114.10                   
    max_ep:  500000                     # defualt:1000, over the ep will auto exit()
    render: yes                        # defualt: false, render the env 
    render_after_ep: 200                # defualt: 0, render afet the ep 