conn: 
    server_worker_num: &ref_server_worker_num 1
    server_ip: 127.0.0.1
    server_frontend_port: 5555
    server_backend_port: 5556
    client_num: 4
    client_retries: 3
    client_timeout: 2500   #ms

RL:
    method: 'DDPG'
    # train_multi_steps: 1       # default: 1, param: 'if_down', 'steps(int)'-> train if down or train after steps    
    reward_gamma: 0.99
    reward_factor: 0.01            # default: 1
    reward_reverse: yes           # dafault: False
    add_data_steps: 'if_down'     # dafault: 1 , param: 'if_down', 'steps(int)'    
    exploration: 300        # train after exploration step
    # action_noise: 'Uhlenbeck'
    action_noise: 'epsilon-greedy'
    state_discrete: yes
    state_shape: [22,]
    action_discrete: no
    action_shape: [1,]    
    action_bound: 3.14159
    
DDPG:
    lr_actor:   0.002  # learning rate for actor (1e-4)
    lr_critic:  0.002  # learning rate for critic
    memory_capacity: 10000
    memory_train_min: 1000 
    batch_size: 32          
    tau: 0.1              # the factor about update network with target network
    

epsilon-greedy:
    value: 1.0
    discount: 0.02    # each step discount it  

actor_NN:
    actor_fc_1: # use default op:'relu' and initializer: 'truncated_normal'
        type: 'fc'
        size: 200
        bias_const: 0.01
        initializer: 'xavier'


critic_state_NN:
    state_fc_1: # use default op:'relu' and initializer: 'truncated_normal'
        type: 'fc'
        size: 200
        bias_const: 0.03
        initializer: 'xavier'


critic_action_NN:
    action_fc_1: # use default op:'relu' and initializer: 'truncated_normal'
        type: 'fc'
        size: 200
        bias_const: 0.01
        initializer: 'xavier'
        
misc:
    model_save_cycle: 30
    model_retrain: yes
    gpu_memory_ratio: 0.03
    random_seed: 3             # t_82 get max reward = 114.10
    max_ep:  1000                       # defualt:1000, over the ep will auto exit()
    render: yes                        # defualt: false, render the env 
    render_after_ep: 100                # defualt: 0, render afet the ep 
    redirect_stdout_2_file: no
    threshold_r: 60
    threshold_successvie_count: 20