conn: 
    server_worker_num: &ref_server_worker_num 1
    server_ip: 127.0.0.1
    server_frontend_port: 5555
    server_backend_port: 5556
    client_num: 1
    client_retries: 3
    client_timeout: 2500   #ms

RL:
    method: 'SARSA'
    state_frames: 1
    state_shape: !!python/tuple [2,]
    action_discrete: yes
    action_num: 4
    train_multi_steps: no
    

SARSA:
    LR: 0.1  # learning rate for actor (1e-4)
    gamma: 0.9  # reward discount
    epsilon-greedy: 0.9